name: delivery_app
description: A delivery app .

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sequence_animation: "^3.0.0"
  animated_text_kit: ^3.0.1
  animations: ^1.1.2
  build_verify: ^1.1.0
  flutter_datetime_picker: ^1.2.8
  modal_progress_hud: ^0.1.3 
  floor_generator: ^0.18.0
  moor: ^3.4.0
  cupertino_icons: ^1.0.0
  route_transitions: ^1.0.2
  mdi: ^3.0.0
  sqlite3_flutter_libs: ^0.3.0
  path_provider: ^1.6.27
  path: ^1.7.0
  flappy_search_bar: ^1.4.1
  sqflite: ^1.3.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^3.4.1
  build_runner: ^1.10.13
  
flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family:  Pacifico
      fonts:
      - asset: fonts/Pacifico/Pacifico-Regular.ttf
    
    - family:  Anton
      fonts:
      - asset: fonts/Anton/Anton-Regular.ttf
    
    - family:  Prata
      fonts:
      - asset: fonts/Prata/Prata-Regular.ttf